language: python

python:
  - '2.7'
  - '3.4'
  - '3.6'
  - 'nightly'

install:
  - pip install Django

script: 'python --version' # placeholder

matrix:
  allow_failures:
    - python: 'nightly'

notifications:
    slack: tech-buddies:B704esrJDxKSumNTvSC5pKbK
